jwt:
  token:
    header: Authorization
    issuer: seunggulee
    client-secret: kakaopayinsurancetlzmfltqlalfqjsgh
    token-validity-in-milliseconds: 300000

spring:
  application:
    name: payment
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  profiles:
    active: default
    include: encrypt
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  port: 9232
  servlet:
    encoding:
      charset: UTF-8

string:
  card-encrypt-separator: '|'
  masking: '*'

logging:
  level:
    root: INFO
    org:
      hirbernate:
        SQL: debug
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
    com:
      kakaoinsurance:
        payment: DEBUG


initialize:
  email: seunggu.lee@kakaoinsurance.com
  password: test1234
  nickname: 카카오페이손해보험
